name: Next.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'nextjs/**'
      - '!websocket-server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'nextjs/**'
      - '!websocket-server/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Cache npm dependencies for nextjs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-nextjs-${{ hashFiles('nextjs/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install dependencies and run tests for nextjs
        working-directory: ./nextjs
        env:
          NEXTAUTH_URL: http://localhost:3000
          GITHUB_CLIENT_ID: ${{ secrets.SECRET_GITHUB_CLIENT }}
          GITHUB_CLIENT_SECRET: ${{ secrets.CLIENT_ID_GITHUB }}
        run: |
          npm ci
          npm run build --if-present
          npm test