name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
    - 'nextjs/**'
    - 'websocket-server/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'nextjs/**'
    - 'websocket-server/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 23
      uses: actions/setup-node@v4
      with:
        node-version: '23.x'
        cache: 'npm'

    - name: Install dependencies and run tests for nextjs
      if: contains(github.event.head_commit.message, 'nextjs')
      working-directory: ./nextjs
      run: |
        npm ci
        npm run build --if-present
        npm test

    - name: Install dependencies and run tests for websocket-server
      if: contains(github.event.head_commit.message, 'websocket-server')
      working-directory: ./websocket-server
      run: |
        npm ci
        npm run build --if-present
        npm test
